server:
 port: 8080

gemini:
 api-keys:
  - AIzaSyCnVXljwD0eNRdgf6IgsdLHJSX0To6PnCE
 endpoint: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
 model-name: models/gemini-2.0-flash

#spring:
# datasource:
#  url: jdbc:postgresql://dxtdb.cf2m6ku2yplo.ap-southeast-2.rds.amazonaws.com:5432/dxtDB
#  username: postgres
#  password: dxtDB123
#  driver-class-name: org.postgresql.Driver

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/rag_db
  username: rag_user
  password: rag_password
  driver-class-name: org.postgresql.Driver

#spring:
# datasource:
#  url: jdbc:postgresql://dxtdb.cf2m6ku2yplo.ap-southeast-2.rds.amazonaws.com:5432/dxtDB
#  username: postgres
#  password: dxtDB123
#  driver-class-name: org.postgresql.Driver

 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
   ddl-auto: validate
  show-sql: true

embedding:
 base-url: http://localhost:8000
 endpoints:
  search: /search
  embed: /embed

logging:
 level:
  root=INFO: