server:
 port: 8080

gemini:
 api-keys:
  - AIzaSyCnVXljwD0eNRdgf6IgsdLHJSX0To6PnCE
 endpoint: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
 model-name: models/gemini-2.0-flash

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/DXTExample
  username: postgres
  password: lytruongtho123
  driver-class-name: org.postgresql.Driver

 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
   ddl-auto: update
  show-sql: true

